# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

timezone: Asia/Seoul

title: GiGong Blog
email: gigong222@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gigong.io" # the base hostname & protocol for your site, e.g. http://example.com

description: >- # this means to ignore newlines
  기공의 블로그 입니다. 주로 프로그래밍 내용을 올립니다. 
  GiGong Blog

github_username: GiGong
github: "https://github.com/GiGong"
tistory: "https://tistory.gigong.io"

# Build settings
markdown: kramdown
highlighter: rouge
include: ['_pages']

category_main : ["C#", "WPF"]

permalink: /:year/:month/:day/:title

start_excerpt: "<!--start excerpt-->"